/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Friend { 'principal' : Principal, 'isBestFriend' : boolean }
export interface GuestProfile {
  'displayName' : string,
  'profilePicture' : [] | [ExternalBlob],
  'guestId' : string,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'video' : [] | [ExternalBlob],
  'sender' : Principal,
  'timestamp' : Time,
  'replyTo' : [] | [bigint],
  'receiver' : Principal,
}
export interface Room {
  'id' : string,
  'creator' : Principal,
  'participants' : Array<string>,
  'joinCode' : string,
  'isGroup' : boolean,
}
export interface RoomMessage {
  'id' : bigint,
  'content' : string,
  'video' : [] | [ExternalBlob],
  'sender' : string,
  'timestamp' : Time,
  'replyTo' : [] | [bigint],
  'roomId' : string,
}
export interface SearchResult {
  'principal' : Principal,
  'username' : string,
  'displayName' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export interface SystemMessage {
  'id' : bigint,
  'content' : string,
  'messageType' : string,
  'timestamp' : Time,
  'roomId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'username' : string,
  'displayName' : string,
  'themeColor' : string,
  'darkMode' : boolean,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFriend' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateGuestProfile' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
  'createOrUpdateProfile' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'createRoom' : ActorMethod<[string, boolean], string>,
  'getAllRooms' : ActorMethod<[[] | [string]], Array<Room>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriendsList' : ActorMethod<[], Array<Friend>>,
  'getGuestProfile' : ActorMethod<[string], [] | [GuestProfile]>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getRoom' : ActorMethod<[string], Room>,
  'getRoomMessages' : ActorMethod<[string, [] | [Time]], Array<RoomMessage>>,
  'getRoomParticipants' : ActorMethod<[string], Array<string>>,
  'getSystemMessages' : ActorMethod<
    [string, [] | [Time]],
    Array<SystemMessage>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinRoom' : ActorMethod<[string, string], undefined>,
  'joinRoomWithCode' : ActorMethod<[string, string], string>,
  'leaveRoom' : ActorMethod<[string, string], undefined>,
  'removeFriend' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<SearchResult>>,
  'sendMessage' : ActorMethod<
    [Principal, string, [] | [bigint], [] | [ExternalBlob]],
    undefined
  >,
  'sendRoomMessage' : ActorMethod<
    [string, string, [] | [bigint], [] | [ExternalBlob]],
    undefined
  >,
  'setRoomParticipants' : ActorMethod<[string, Array<string>], undefined>,
  'setSystemMessage' : ActorMethod<[string, string, string], undefined>,
  'toggleBestFriend' : ActorMethod<[Principal], undefined>,
  'updateProfilePicture' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];