/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Call {
  'id' : bigint,
  'startTime' : Time,
  'status' : CallStatus,
  'endTime' : [] | [Time],
  'caller' : Principal,
  'receiver' : Principal,
}
export type CallStatus = { 'pending' : null } |
  { 'missed' : null } |
  { 'ended' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export type ExternalBlob = Uint8Array;
export interface Friend { 'principal' : Principal, 'isBestFriend' : boolean }
export interface Message {
  'id' : bigint,
  'content' : string,
  'video' : [] | [ExternalBlob],
  'sender' : Principal,
  'timestamp' : Time,
  'replyTo' : [] | [bigint],
  'receiver' : Principal,
}
export interface SearchResult {
  'principal' : Principal,
  'username' : string,
  'displayName' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'username' : string,
  'displayName' : string,
  'themeColor' : string,
  'darkMode' : boolean,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFriend' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'getCallHistory' : ActorMethod<[], Array<Call>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriendsList' : ActorMethod<[], Array<Friend>>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initiateCall' : ActorMethod<[Principal], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFriend' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<SearchResult>>,
  'sendMessage' : ActorMethod<
    [Principal, string, [] | [bigint], [] | [ExternalBlob]],
    undefined
  >,
  'toggleBestFriend' : ActorMethod<[Principal], undefined>,
  'updateCallStatus' : ActorMethod<[bigint, CallStatus], undefined>,
  'updateProfilePicture' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];