/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Room = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'participants' : IDL.Vec(IDL.Text),
  'joinCode' : IDL.Text,
  'isGroup' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'themeColor' : IDL.Text,
  'darkMode' : IDL.Bool,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Friend = IDL.Record({
  'principal' : IDL.Principal,
  'isBestFriend' : IDL.Bool,
});
export const GuestProfile = IDL.Record({
  'displayName' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'guestId' : IDL.Text,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'video' : IDL.Opt(ExternalBlob),
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'replyTo' : IDL.Opt(IDL.Nat),
  'receiver' : IDL.Principal,
});
export const RoomMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'video' : IDL.Opt(ExternalBlob),
  'sender' : IDL.Text,
  'timestamp' : Time,
  'replyTo' : IDL.Opt(IDL.Nat),
  'roomId' : IDL.Text,
});
export const SystemMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'messageType' : IDL.Text,
  'timestamp' : Time,
  'roomId' : IDL.Text,
});
export const SearchResult = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFriend' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateGuestProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'createRoom' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
  'getAllRooms' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(Room)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFriendsList' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
  'getGuestProfile' : IDL.Func([IDL.Text], [IDL.Opt(GuestProfile)], ['query']),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getRoom' : IDL.Func([IDL.Text, IDL.Text], [Room], ['query']),
  'getRoomMessages' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(Time)],
      [IDL.Vec(RoomMessage)],
      ['query'],
    ),
  'getRoomParticipants' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getSystemMessages' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(Time)],
      [IDL.Vec(SystemMessage)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'joinRoomWithCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'leaveRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeFriend' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'sendRoomMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'setRoomParticipants' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'setSystemMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'toggleBestFriend' : IDL.Func([IDL.Principal], [], []),
  'updateProfilePicture' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Room = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'participants' : IDL.Vec(IDL.Text),
    'joinCode' : IDL.Text,
    'isGroup' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'themeColor' : IDL.Text,
    'darkMode' : IDL.Bool,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Friend = IDL.Record({
    'principal' : IDL.Principal,
    'isBestFriend' : IDL.Bool,
  });
  const GuestProfile = IDL.Record({
    'displayName' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'guestId' : IDL.Text,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'video' : IDL.Opt(ExternalBlob),
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'replyTo' : IDL.Opt(IDL.Nat),
    'receiver' : IDL.Principal,
  });
  const RoomMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'video' : IDL.Opt(ExternalBlob),
    'sender' : IDL.Text,
    'timestamp' : Time,
    'replyTo' : IDL.Opt(IDL.Nat),
    'roomId' : IDL.Text,
  });
  const SystemMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'messageType' : IDL.Text,
    'timestamp' : Time,
    'roomId' : IDL.Text,
  });
  const SearchResult = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFriend' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateGuestProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'createRoom' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
    'getAllRooms' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(Room)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFriendsList' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
    'getGuestProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuestProfile)],
        ['query'],
      ),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getRoom' : IDL.Func([IDL.Text, IDL.Text], [Room], ['query']),
    'getRoomMessages' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(Time)],
        [IDL.Vec(RoomMessage)],
        ['query'],
      ),
    'getRoomParticipants' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getSystemMessages' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(Time)],
        [IDL.Vec(SystemMessage)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'joinRoomWithCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'leaveRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeFriend' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'sendRoomMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'setRoomParticipants' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'setSystemMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'toggleBestFriend' : IDL.Func([IDL.Principal], [], []),
    'updateProfilePicture' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };