/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CallStatus = IDL.Variant({
  'pending' : IDL.Null,
  'missed' : IDL.Null,
  'ended' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const Call = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'status' : CallStatus,
  'endTime' : IDL.Opt(Time),
  'caller' : IDL.Principal,
  'receiver' : IDL.Principal,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'themeColor' : IDL.Text,
  'darkMode' : IDL.Bool,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Friend = IDL.Record({
  'principal' : IDL.Principal,
  'isBestFriend' : IDL.Bool,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'video' : IDL.Opt(ExternalBlob),
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'replyTo' : IDL.Opt(IDL.Nat),
  'receiver' : IDL.Principal,
});
export const SearchResult = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFriend' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'getCallHistory' : IDL.Func([], [IDL.Vec(Call)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFriendsList' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initiateCall' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFriend' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'toggleBestFriend' : IDL.Func([IDL.Principal], [], []),
  'updateCallStatus' : IDL.Func([IDL.Nat, CallStatus], [], []),
  'updateProfilePicture' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CallStatus = IDL.Variant({
    'pending' : IDL.Null,
    'missed' : IDL.Null,
    'ended' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Call = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'status' : CallStatus,
    'endTime' : IDL.Opt(Time),
    'caller' : IDL.Principal,
    'receiver' : IDL.Principal,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'themeColor' : IDL.Text,
    'darkMode' : IDL.Bool,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Friend = IDL.Record({
    'principal' : IDL.Principal,
    'isBestFriend' : IDL.Bool,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'video' : IDL.Opt(ExternalBlob),
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'replyTo' : IDL.Opt(IDL.Nat),
    'receiver' : IDL.Principal,
  });
  const SearchResult = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFriend' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'getCallHistory' : IDL.Func([], [IDL.Vec(Call)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFriendsList' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initiateCall' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFriend' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'toggleBestFriend' : IDL.Func([IDL.Principal], [], []),
    'updateCallStatus' : IDL.Func([IDL.Nat, CallStatus], [], []),
    'updateProfilePicture' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };